---
- hosts: hp1
  tasks:
    - name: Add the user 'bill' 
      user:
        name: bill
        comment: nothing
        uid: 1040
        group: bill

    - name: install the latest version of httpd
      yum:
        name: httpd
        state: latest

    - name: remove the Apache package
      yum:
        name: httpd
        state: absent

    - name: install the latest version of nginx
      yum:
        name: nginx
        state: latest


    - name: Set authorized key taken from file
      authorized_key:
        user: root
        state: present
        key: "{{ lookup('file', '/root/.ssh/id_rsa.pub') }}"
